version: "3.9"
services:
  root-web:
    build: .
    restart: always
  dev:
    build: "dev"
    restart: always
  heysteimke:
    build: "heysteimke"
    restart: always
  rkpsearch:
    build: "rkpsearch"
    restart: always
  steimkebioladen:
    build: "steimkebioladen"
    restart: always
  nginx-proxy:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   
  db:
    image: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
    volumes:
      - "dbvol:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  dbvol:
  