version: "3.9"
services:
  root-web:
    build: .
    restart: always
  dev:
    build: "dev"
    restart: always
  heysteimke:
    build: "heysteimke"
    restart: always
  rkpsearch:
    build: "rkpsearch"
    restart: always
  steimkebioladen:
    build: "steimkebioladen"
    restart: always
  hsweb:
    build: "hsweb"
    restart: always
  download:
    image: httpd
    restart: always
    volumes:
      - "./download/:/usr/local/apache2/htdocs/download/:ro"
  steimkebioladen:
    build: "hsweb"
    restart: always
  nginx-proxy:
    build: "proxy"
    restart: always
    ports:
      - "80:80"
  db:
    image: ${DB_IMAGE}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
    volumes:
      - "dbvol:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  dbvol:
  
