version: "3.9"
services:
  root-web:
    build: .
    ports: 
      - "8081:80"
  dev:
    build: "dev"
    ports: 
      - "8082:80"
  heysteimke:
    build: "heysteimke"
    ports: 
      - "8083:80"
  rkpsearch:
    build: "rkpsearch"
    ports: 
      - "8084:80"
  steimkebioladen:
    build: "steimkebioladen"
    ports: 
      - "8085:80"
  nginx-proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   
  