version: "3"
services:
  root-web:
    build: .
    restart: always
  dev:
    build: "dev"
    restart: always
  heysteimke:
    build: "heysteimke"
    restart: always
  rkpsearch:
    build: "rkpsearch"
    restart: always
  steimkebioladen:
    build: "steimkebioladen"
    restart: always
  hsweb:
    build: "hsweb"
    restart: always
  downloadweb:
    image: httpd
    restart: always
    volumes:
      - "download:/usr/local/apache2/htdocs/"
  downloadftp:
    image: fauria/vsftpd
    restart: always
    volumes:
      - "download:/home/vsftpd/admin"
    ports:
      - "20-21:20-21"
      - "21100-21110:21100-21110"
    environment:
      - PASV_ADDRESS=127.0.0.1 
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
  nginx-proxy:
    build: "proxy"
    restart: always
    ports:
      - "80:80"
  db:
    image: ${DB_IMAGE}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
    volumes:
      - "dbvol:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
  nuget:
    image: sunside/simple-nuget-server
    restart: always
    environment:
      NUGET_API_KEY: ${NUGET_APIKEY}
    volumes:
      - "nugetpack:/var/www/packagefiles"
      - "nugetdb:/var/www/db"
volumes:
  dbvol:
  download:
  nugetpack:
  nugetdb: