version: "3"
services:
  root-web:
    image: thebanger/web-root
    restart: always
  dev:
    image: thebanger/web-dev
    restart: always
  heysteimke:
    image: thebanger/web-heysteimke
    restart: always
  rkpsearch:
    image: thebanger/web-rkpsearch
    restart: always
  steimkebioladen:
    image: thebanger/web-steimkebioladen
    restart: always
  hsweb:
    image: thebanger/web-hsweb
    restart: always
  downloadweb:
    image: httpd
    restart: always
    volumes:
      - "download:/usr/local/apache2/htdocs/"
  downloadftp:
    image: fauria/vsftpd
    restart: always
    volumes:
      - "download:/home/vsftpd/admin"
    ports:
      - "20-21:20-21"
      - "21100-21110:21100-21110"
    environment:
      - PASV_ADDRESS=127.0.0.1 
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
  nginx-proxy:
    image: thebanger/proxy
    restart: always
    ports:
      - "80:80"
  db:
    image: mysql
    restart: always
    volumes:
      - "dbvol:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
volumes:
  dbvol:
  download: