version: "3"
services:
  root-web:
    image: thebanger/web-root
    restart: always
  dev:
    image: thebanger/web-dev
    restart: always
  heysteimke:
    image: thebanger/web-heysteimke
    restart: always
  rkpsearch:
    image: thebanger/web-rkpsearch
    restart: always
  steimkebioladen:
    image: thebanger/web-steimkebioladen
    restart: always
  hsweb:
    image: thebanger/web-hsweb
    restart: always
  downloadweb:
    image: httpd
    restart: always
    volumes:
      - "download:/usr/local/apache2/htdocs/"
  downloadftp:
    image: fauria/vsftpd
    restart: always
    volumes:
      - "download:/home/vsftpd/admin"
    ports:
      - "20-21:20-21"
      - "21100-21110:21100-21110"
    environment:
      - PASV_ADDRESS=127.0.0.1 
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
  nginx-proxy:
    build: "proxy"
    restart: always
    ports:
      - "80:80"
    environment:
     - SERVER_HOSTNAME=${SERVER_HOSTNAME}
  db:
    image: ${DB_IMAGE}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
    volumes:
      - "dbvol:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
  nuget:
    image: sunside/simple-nuget-server
    restart: always
    environment:
      NUGET_API_KEY: ${NUGET_APIKEY}
    volumes:
      - "nugetpack:/var/www/packagefiles"
      - "nugetdb:/var/www/db"
  gitlab:
    image: "gitlab/gitlab-ee:latest"
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${SERVER_HOSTNAME}/gitlab'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        letsencrypt['enable'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "http",
          "CUSTOM_HEADER" => "VALUE"
        }
    volumes:
      - "gitlabconfig:/etc/gitlab"
      - "gitlablog:/var/log/gitlab"
      - "gitlabdata:/var/opt/gitlab"

volumes:
  dbvol:
  download:
  nugetpack:
  nugetdb:
  gitlabconfig:
  gitlablog:
  gitlabdata: